# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1a5351b9b54bd96e96760329ddc90bbcda126d1f6a6383306a736a3b4ff684642c62a45a2448b9b37c9d6e033eca535ecefff9f10bee24d4693545908f4669a

test:
  secret_key_base: 09cfd4080241ca3b88f124a151c5f0e5e124364cc558ee6b32ec2e0f716e7c917cd9ee9edbde4168fce17bc5760f648c9802ab2f10b4760286135974eb1d7ef5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
